### ISSUE TITLE
LruMap of maximumSize 1 crashes on second insert

### ISSUE THREAD

**Issue by srawlins** [google/quiver-dart#475]
```dart
import 'package:quiver/collection.dart' show LruMap;

void main() {
  final map = LruMap<int, String>(maximumSize: 1);
  map.putIfAbsent(7, () => 'seven');
  map.putIfAbsent(8, () => 'eight');
}
```

```none
$ dart --version
Dart VM version: 2.0.0-dev.69.2 (Mon Jul 23 17:10:56 2018 +0200) on "macos_x64"
srawlins-macbookair:dart-quiver srawlins$ dart a.dart 
Unhandled exception:
NoSuchMethodError: The setter 'next=' was called on null.
Receiver: null
Tried calling: next=null
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
#1      LinkedLruHashMap._removeLru (file:///Users/srawlins/code/dart-quiver/lib/src/collection/lru_map.dart:379:11)
#2      LinkedLruHashMap.putIfAbsent (file:///Users/srawlins/code/dart-quiver/lib/src/collection/lru_map.dart:182:7)
#3      main (file:///Users/srawlins/code/dart-quiver/a.dart:6:7)
#4      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

**Comment by cbracken** [comment]
Fixed by #475 by @wills
