### ISSUE TITLE
Should Optional.transform() return Optional.absent() with type param?

### ISSUE THREAD

**Issue by minia68** [google/quiver-dart#577]
Optional.transform() with null optional value return Optional.absent() with type Null, which throw exception
```
import 'package:quiver/core.dart';

void main() {
  C c;
  Optional.fromNullable(c).transform((c) => c.str).or('');
}

class C {
  final String str;

  C(this.str);
}
```
```
Unhandled exception:
type 'String' is not a subtype of type 'Null' of 'defaultValue'
#0      Optional.or (package:quiver/src/core/optional.dart)
#1      calculate (package:inject_test/inject_test.dart:5:52)
#2      main (file:///data/cde/fl/inject_test/bin/main.dart:4:3)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

**Comment by cbracken** [comment]
Thanks for filing this. Also filed as #584. Fixed in  #587 and released in 2.1.3.
